server:
  port: 8082
  
spring:
  application:
    name: DC-API
    
  datasource:
    username: null
    password: null
    url:      null
  
  boot:
    admin:
      client:
        url: null
       
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        